name: MonoItem
api-version: 1.13
version: 1.0
author: TiveCS
main: team.rehoukrelstudio.monoitem.MonoItem
softdepend:
  - Vault
  - MythicMobs
  - RPGItems
  - HolographicDisplays
commands:
    identify:
      description: Identify item on hand
      permission: monoitem.command.identify
      aliases: [appraise]
    monoitem:
      permission: monoitem.command
      description: monoitem editor main command
      aliases: [mi, monoi, mitem, monitem, moni]