file-version: 1.0

trigger:
  armor:
    - SNEAK
    - DAMAGE_TAKEN
    - PROJECTILE_HIT
    - PROJECTILE_SHOOT
    - PROJECTILE_HIT_BLOCK
  weapon:
    - SNEAK
    - DAMAGE
    - PROJECTILE_HIT
    - PROJECTILE_SHOOT
    - PROJECTILE_HIT_BLOCK
    - LEFT_CLICK
    - RIGHT_CLICK

ability-base:
  weapon:
    - ARROW_STORM:{cooldown:80=120;amount=5=12;}
    - REFLECTION:{cooldown:120=140;chance:40=55;}
    - VORPAL_SLASH:{cooldown:200=350;result:115=135;}
  armor:
    - REFLECTION:{cooldown:220=300;chance:20=25;}
    - IRON_SKIN:{cooldown:160=200;chance:30=60;knockbackpower:1=2.5;result:25=35;}
    - LEAP:{cooldown:200=250;result=2.5=3;}

stats-base:
  default:
    - PHYSICAL_DEFENSE:0.3=1.7
    - MAGICAL_DEFENSE:0.1=1
    - BLOCK_RATE:0.2=2
    - BLOCK_AMOUNT:0.5=5
    - DODGE:0.37=1.1
    - CRITICAL_RESISTANCE:0.12=3
    - ATTACK_SPEED:-12=12
    - DECREASE_DAMAGE:10=15
    - PHSYICAL_DAMAGE:8.75=13.5
    - MAGICAL_DAMAGE:1.5=2.95
    - CRITICAL_RATE:0.7=1.07
    - CRITICAL_DAMAGE:1=4
    - INCREASE_DAMAGE:2=2.5
    - BLOCK_PENETRATION:0.12=3
  weapon:
    - PHYSICAL_DAMAGE:1.1=2.1
    - MAGICAL_DAMAGE:0.6=1.2
    - CRITICAL_RATE:0.7=1.07
    - CRITICAL_DAMAGE:1=4
    - INCREASE_DAMAGE:2=2.5
    - BLOCK_PENETRATION:0.12=3
    - ATTACK_SPEED:-12=12
  armor:
    - PHYSICAL_DEFENSE:0.1=0.74
    - MAGICAL_DEFENSE:0.1=0.74
    - BLOCK_RATE:0.2=2
    - BLOCK_AMOUNT:0.5=5
    - DODGE:0.37=1.1
    - CRITICAL_RESISTANCE:0.12=3
    - ATTACK_SPEED:-12=12
    - INCREASE_DAMAGE:2=2.5
    - BLOCK_PENETRATION:0.12=3

unidentified-item:
  settings:
    result-formula: '%result%*(%multiplier%*%level%/(%multiplier%*1/3))'
    durability:
      unbreakable: true # Unbreakable as default
      base: 900 # Durability base will be multiplied by multiplier-result on specify table
    identifier-level:
      default: 1
    identify-price:
      multiply-price-per-level: true
      money: 1000
      xp: 0
      xp_level: 0
    use-saved-item: false
    vanilla-mob-drop: false
    mythicmobs-drop:
      enable: true
      use-prefix: true
      mob-displayname-prefix: '&7Lv. &c%level% &4' # Use for checking
  table:
    Legendary:
      mob-drop-chance: 0.01
      multiplier-result: 2.4
      identify-price-multiplier: 3
      prefix: '&b'
      durability:
        unbreakable: true # Force unbreakable
        base: 7700 # Forcing have base on this value
      stats:
        amount:
          minimum: 3
          maximum: 5
      ability:
        amount:
          minimum: 1
          maximum: 3
      item:
        display-name: '&bUnidentified Item'
        lore:
          - ' '
          - '&bLegendary item'
    Rare:
      mob-drop-chance: 0.087
      multiplier-result: 1.72
      identify-price-multiplier: 2
      prefix: '&d'
      durability:
        unbreakable: true # Force unbreakable
        base: 2700 # Forcing have base on this value
      stats:
        amount:
          minimum: 2
          maximum: 4
      ability:
        amount:
          minimum: 1
          maximum: 2
      item:
        display-name: '&dUnidentified Item'
        lore:
          - ' '
          - '&dRare item'
    Unique:
      mob-drop-chance: 0.2
      multiplier-result: 1.2
      identify-price-multiplier: 1.25
      prefix: '&e'
      durability:
        unbreakable: true # Force unbreakable
        base: 870 # Forcing have base on this value
      stats:
        amount:
          minimum: 1
          maximum: 3
      ability:
        amount:
          minimum: 0
          maximum: 1
      item:
        display-name: '&eUnidentified Item'
        lore:
          - ' '
          - '&eUnique item'
    Common:
      mob-drop-chance: 0.4
      multiplier-result: 1
      identify-price-multiplier: 1
      prefix: '&a'
      durability:
        unbreakable: false # Force unbreakable
        base: 597 # Forcing have base on this value
      stats:
        amount:
          minimum: 1
          maximum: 2
      ability:
        amount:
          minimum: 0
          maximum: 0
      item:
        display-name: '&aUnidentified Item'
        lore:
          - ' '
          - '&aCommon item'
    Trash:
      mob-drop-chance: 0.7
      multiplier-result: 0.5
      identify-price-multiplier: 0.5
      prefix: '&8'
      durability:
        unbreakable: false # Force unbreakable
        base: 297 # Forcing have base on this value
      stats:
        amount:
          minimum: 1
          maximum: 1
      ability:
        amount:
          minimum: 0
          maximum: 0
      item:
        display-name: '&8Unidentified Item'
        lore:
          - ' '
          - '&7Trash item'